# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'
includes:
  cluster-01: 
    taskfile: ../../clusters/cluster-01/bootstrap/taskfile.yaml
    internal: true
  cluster-02: 
    taskfile: ../../clusters/cluster-02/bootstrap/taskfile.yaml
    internal: true
  cluster-03: 
    taskfile: ../../clusters/cluster-03/bootstrap/taskfile.yaml
    internal: true
tasks:

  run-*-*:
    desc: manage clusters
    vars:
      NUM: '{{index .MATCH 0}}'
      CMD: '{{index .MATCH 1}}'
    cmds:
    - task: 'cluster-{{ .NUM }}:{{ .CMD }}'