# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'
tasks:

  run-*-*-*:
    desc: manage argocd root applications
    vars:
      CMD: '{{index .MATCH 0}}'
      NUM: '{{index .MATCH 1}}'
      ENV: '{{index .MATCH 2}}'
    cmds:
    - kubectl {{ .CMD }} -f clusters/cluster-{{ .NUM }}/environments/{{ .ENV }}/root.yaml
