# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

includes:
  cluster:
    taskfile: control/tasks/cluster.yaml
    internal: false
  apps:
    taskfile: control/tasks/root-apps.yaml
    internal: false
tasks:
  default: task -a