# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'
env:
  DEV: clusters/cluster-01/environments/dev/root.yaml

tasks:
  default: task -a

  apply-dev:
    desc: ''
    cmds:
    - kubectl apply -f ${DEV}
    
  delete-dev:
    desc: ''
    cmds:
    - kubectl delete -f ${DEV}