# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

includes:
  cluster-01: clusters/cluster-01/bootstrap/taskfile.yaml
  cluster-02: clusters/cluster-02/bootstrap/taskfile.yaml

tasks:
  default: task -a
  test:
  - task: cluster-01:test

  cluster-*-*:
    vars:
      NUM: '{{index .MATCH 0}}'
      CMD: '{{index .MATCH 1}}'
    cmds:
    - task: 'cluster-{{ .NUM }}:{{ .CMD }}'
