# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

includes:
  cluster:
    taskfile: control/tasks/cluster.yaml
    internal: true
  apps:
    taskfile: control/tasks/root-apps.yaml
    internal: true
tasks:
  start-*: 
  - task: cluster:run-{{index .MATCH 0}}-start
  stop-*: 
  - task: cluster:run-{{index .MATCH 0}}-stop
  delete-*: 
  - task: cluster:run-{{index .MATCH 0}}-delete