apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name dpl-kustomize-01

spec:
  replicas: 1
  minReadySeconds: 10
  
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  selector:
    matchLabels:
      pod: &container pod-kustomize-01

  template:
    metadata:
      labels:
        pod: *container
    spec:
      containers:
      - name: *name
        image: docker.io/bokovets/kuber:v1.0
        ports:
        - name: app-port
          containerPort: 8000