apiVersion: v1
kind: Service
metadata:
  name: svc-np-kuber-app # потом будет доступна в подах как env
  # labels:
  #   service: myapp-service-label

spec:
  selector: # matchLabels not woked
    pod: po-kuber-app  # ref лейбл пода -> generate endpoints for pods automatically
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: app-port # -> pod port name

  type: NodePort # NodePort | ClusterIP | LoadBalancer | ExternalName 

# for load balancer
# kubectl get service myapp-service-name -> see external ip
# from browser http://<external.ip>:<service.port>

# for cluster ip from pod
# cat /etc/resolv.conf - все доменные имена
# curl http://myapp-service-name.default.svc.cluster.local