apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-svc-np-kuber-app
spec:
  rules:
   - host: app.example.com
     http:
        paths:
          - pathType: Prefix  # потдомены разрешены
            path: /
            backend:
              service:

                name: {{ .Release.Name }}-service # -> svc name
                port: 
                  number: 80 # svc target traffic to port:80
       
                 
  #  - host: app-v3.example.com
  #    http:
  #       paths:
  #         - pathType: Exact
  #           path: /
  #           backend:
  #             service:
  #               name: kuber-service-v3
  #               port: 
  #                 number: 80