apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name      : current-dev-root
  namespace : argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path   : "clusters/cluster-01/environments/dev/applications"
    repoURL: "https://github.com/linitsh/argo-adv-test.git"
    targetRevision: HEAD
  destination:
    name     : in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
      